// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	CategoryID int64  `json:"category_id"`
	Name       string `json:"name"`
}

type Comment struct {
	CommentID     int64     `json:"comment_id"`
	CommentText   string    `json:"comment_text"`
	CreatedAt     time.Time `json:"created_at"`
	TicketID      int64     `json:"ticket_id"`
	UserCommented string    `json:"user_commented"`
}

type Ticket struct {
	TicketID     int64          `json:"ticket_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ClosedAt     sql.NullTime   `json:"closed_at"`
	CategoryID   int64          `json:"category_id"`
	UserAssigned string         `json:"user_assigned"`
	AssignedTo   sql.NullString `json:"assigned_to"`
}
