// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	DeleteCategory(ctx context.Context, categoryID int64) error
	DeleteComment(ctx context.Context, commentID int64) error
	DeleteTicket(ctx context.Context, ticketID int64) error
	GetCategory(ctx context.Context, categoryID int64) (Category, error)
	GetCommentForUpdate(ctx context.Context, commentID int64) (Comment, error)
	GetTicket(ctx context.Context, ticketID int64) (Ticket, error)
	GetTicketForUpdate(ctx context.Context, ticketID int64) (Ticket, error)
	ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]Ticket, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListComments(ctx context.Context, arg ListCommentsParams) ([]Comment, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
}

var _ Querier = (*Queries)(nil)
