name: Deploy to production

on:
  push:
    branches: [ release ]

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2



    - name: Docker login 
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -U $DOCKER_USER -p $DOCKER_PASS
        
    - name: Build, tag, and push image to Amazon ECR
      env:
        REPOSITORY: nadersameh8/ticketing_support
        IMAGE_TAG: ${{ github.sha }}

      run: |
        docker build -t $REPOSITORY:$IMAGE_TAG -t $REPOSITORY:latest .
        docker push -a $REPOSITORY
